config/routes.rb
EdgeOfScience::Application.routes.draw do
  
  
  devise_for :users
  resources :edits do
      member do
    put "like", to: "edits#upvote"
    put "dislike", to: "edits#downvote"
    end
  end
  
  root  'topics#index'
  resources :topics
  match '/about',   to: 'static_pages#about',   via: 'get'  
  match '/contacts',     to: 'contacts#new',    via: 'get'

end

app/models/edit.rb
class Edit < ActiveRecord::Base
  acts_as_votable
  belongs_to :user
  belongs_to :topic
  
 # validates :user_id, presence: true
#  validates :description, presence: true, length: { maximum: 2000 }
  validates :topic_id, presence: true
  validates :chg, presence: true
    
  default_scope -> { order('created_at DESC') }

  def score
    self.get_upvotes.size - self.get_downvotes.size
  end
  
  def self.unsolved_feed
    #unsolved_ids = "SELECT name FROM problems WHERE user_id > 0" 
    #where("(#{unsolved_ids})")
    Edit.all
  end
end

app/models/topic.rb
class Topic < ActiveRecord::Base
  acts_as_nested_set
  
  belongs_to :user
  has_many :change
  
  validates :name, presence: true
  validates :user_id, presence: true
  validates :description, presence: true, length: { maximum: 2000 }
#  make_voteable
    
  default_scope -> { order('created_at DESC') }


  def self.unsolved_feed
    #unsolved_ids = "SELECT name FROM problems WHERE user_id > 0" 
    #where("(#{unsolved_ids})")
    Topic.all
  end
  
  def self.short_collection_to_json()
    arr = self.short_collection_to_json_help()
    arr.to_json.html_safe
  end
  
   def self.short_collection_to_json_help(collection = self.roots)
    collection.inject([]) do |arr, model|
      if model.parent.nil?
        parent_name=nil
      else
        parent_name=model.parent.name
      end
      
      if model.children.empty?
         arr << { name: model.name, parent: parent_name, num: model.id  }
      else
         arr << { name: model.name, parent: parent_name, num: model.id, children: short_collection_to_json_help(model.children) }
      end
    end
  end
end

app/models/user.rb
class User < ActiveRecord::Base
# Include default devise modules. Others available are:
# :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  
         before_create :create_remember_token
  
         before_save { email.downcase! }
  
  validates :name, presence: true, length: { maximum: 50 }
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-]+(?:\.[a-z\d\-]+)*\.[a-z]+\z/i
  validates :email, presence:   true,
            format:     { with: VALID_EMAIL_REGEX },
            uniqueness: { case_sensitive: false }
  validates :password, length: { minimum: 6 }
  
  has_many :topics
  has_many :edits

  def User.hash(token)
    Digest::SHA1.hexdigest(token.to_s)
  end

  def User.new_remember_token
    SecureRandom.urlsafe_base64
  end
 
  # def asked_problems_feed
    # self.problems.all
  # end
  
  
  private

    def create_remember_token
      self.remember_token = User.hash(User.new_remember_token)
    end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  
  before_action :configure_devise_permitted_parameters, if: :devise_controller?

  protected
    
  
    def configure_devise_permitted_parameters
    registration_params = [:name, :bio, :email, :password, :password_confirmation]
    edit_params = [:name, :bio, :email, :password, :password_confirmation]

    if params[:action] == 'update'
      devise_parameter_sanitizer.for(:account_update) {
        |u| u.permit(edit_params << :current_password)
      }
    elsif params[:action] == 'create'
      devise_parameter_sanitizer.for(:sign_up) {
        |u| u.permit(registration_params)
      }
    end
  end
end

app/controllers/edits_controller.rb
require 'will_paginate/array'

class EditsController < ApplicationController
  #before_action :correct_user,   only: :destroy
  before_filter :authenticate_user!, :except => [:index, :show]
  respond_to :html, :js

  # GET /edits
  # GET /edits.json
  def index
    @feed_items = Edit.unsolved_feed.paginate(page: params[:page])
  end


  # GET /edits/1
  # GET /edits/1.json
  def show
  end
 

  # GET /edits/1/edit
  def edit
  end

  # POST /edits
  # POST /edits.json
  def create
    @edit = current_user.edits.build(edit_params)

    respond_to do |format|
      if @edit.save
        format.html { redirect_to root_path, notice: 'edit was successfully created.' }
        format.json { render action: 'show', status: :created, location: @edit }
      else
        format.html { render action: 'new' }
        format.json { render json: @edit.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /edits/1
  # DELETE /edits/1.json
  def destroy
    @edit.destroy
    respond_to do |format|
      format.html { redirect_to edits_url }
      format.json { head :no_content }
    end
  end
  
  def upvote
    @edit = Edit.find(params[:id])
    @edit.upvote_from current_user
    if @edit.score > 3
      if @edit.chg == "DELETE"
        @edit.topic.destroy
      end
    end
    redirect_to edits_path
        respond_to do |format|
          format.html{ redirect_to edits_url }
          format.js
        end      
  end
  
  def downvote
    @edit = Edit.find(params[:id])
    @edit.downvote_from current_user
    if @edit.score < -3
      @edit.destroy
    end
    redirect_to edits_path
        respond_to do |format|
          format.html{ redirect_to edits_url }
          format.js
        end
  end
  
  
  private
    # Use callbacks to share common setup or constraints between actions.


    # Never trust parameters from the scary internet, only allow the white list through.
    def edit_params
      params.require(:topic).permit(:user_id, :chg , :topic_id, :topic, :description)
    end
    
   def correct_user
      @edit = current_user.edits.find_by(id: params[:id])
      redirect_to root_url if @edit.nil?
    end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController

  def about
  end
  
  # def contact
  # end
end

app/controllers/topics_controller.rb
class TopicsController < ApplicationController
  before_action :set_topic, only: [:show, :edit, :update, :destroy]
  before_filter :authenticate_user!, :except => [:index, :show]
  layout "home"

  # GET /topics
  # GET /topics.json
  def index
    respond_to do |format|
      format.html {  @topics = Topic.all  }
      format.json { render json: Topic.short_collection_to_json()}
    end
  end

  # GET /topics/1
  # GET /topics/1.json
  def show
  end

  # GET /topics/new
  def new
    @topic = Topic.new
  end

  # GET /topics/1/edit
  def edit
  end

  # POST /topics
  # POST /topics.json
  def create
    @topic = current_user.topics.build(topic_params)

    respond_to do |format|
      if @topic.save
        format.html { redirect_to root_path, notice: 'Topic was successfully created.' }
        format.json { render action: 'show', status: :created, location: @topic }
      else
        format.html { render action: 'new' }
        format.json { render json: @topic.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /topics/1
  # PATCH/PUT /topics/1.json
  def update
    respond_to do |format|
      if @topic.update(topic_params)
        format.html { redirect_to root_path, notice: 'Topic was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @topic.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /topics/1
  # DELETE /topics/1.json
  def destroy
    @topic.destroy
    respond_to do |format|
      format.html { redirect_to topics_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_topic
      @topic = Topic.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def topic_params
      params.require(:topic).permit(:user_id, :name, :description, :parent_id)
    end
    
   def correct_user
      @topic = current_user.topics.find_by(id: params[:id])
      redirect_to root_url if @topic.nil?
   end
end

app/helpers/application_helper.rb
module ApplicationHelper

  # Returns the full title on a per-page basis.

  def full_title(page_title)
    base_title = "SciEdge"
    if page_title.empty?
      base_title
    else
      "#{base_title} | #{page_title}"
    end
  end
end

app/helpers/topic_helper.rb
module TopicHelper
end

app/helpers/user_helper.rb
module UserHelper
end

app/views/edits/_downvote.html.erb
<%= link_to "", dislike_edit_path(feed_item), method: :put, remote: true, class: "glyphicon glyphicon-arrow-down" %>

app/views/edits/_upvote.html.erb
<%= link_to "", like_edit_path(feed_item) , method: :put, remote: true, class: "glyphicon glyphicon-arrow-up"  %>

app/views/edits/_vote_count.html.erb
<%= feed_item.score %>

app/views/edits/_voting_form.html.erb
  		<div id="voting_form<%= feed_item.id %>">	
   				 <%=  render 'upvote',  feed_item: feed_item%>
   				 <%=  render 'downvote', feed_item: feed_item %>
   				 <span><%= render 'vote_count' , feed_item: feed_item %></span>
  		</div>

app/views/edits/downvote.js.erb
$("#voting_form<%= feed_item.id %>").html(" <%= escape_javascript( render 'edits/downvote' ) %>")
$("#voting_form<%= feed_item.id %>").html(" <%= escape_javascript( render 'edits/vote_count' ) %>")

app/views/edits/index.html.erb
<div class ="container">
 <div class="row">
	<div class="span8">
      <h3>Proposed Edits</h3>
      <%= render 'shared/feed_list' %>
    </div>
  </div>
</div>

app/views/edits/upvote.js.erb
$("#voting_form<%= feed_item.id %>").html(" <%= escape_javascript( render 'edits/upvote' ) %>")
$("#voting_form<%= feed_item.id %>").html(" <%= escape_javascript( render 'edits/vote_count' ) %>")

app/views/layouts/_footer.html.erb
<footer>

  	<div class="row">
  	<div class="col-lg-12">
    <ul class="nav navbar-nav navbar-left">
      <li><%= link_to "About",   about_path %></li>
    </ul>
    </div>
    </div>
 
</footer>

app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top navbar-default">
  <div class="navbar-inner">
    <div class="container">
   	 <div class="navbar-header">

      <%= link_to "SciEdge", root_path, id: "logo", class: "navbar-brand" %>
      </div>
      <nav>
        <ul class="nav navbar-nav navbar-right">
          <li><%= link_to "Home", root_path %></li>
          <li><%= link_to "Edits", edits_path %></li>


			<% if user_signed_in? %>

              <li id="fat-menu" class="dropdown">
                <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                  Account <b class="caret"></b>
                </a>
                <ul class="dropdown-menu">
                  <li><%= link_to 'Edit profile', edit_user_registration_path %></li>
                  <li class="divider"></li>
                  <li><%= link_to "Logout", destroy_user_session_path, method: :delete %></li>
                </ul>
              </li>
          <% else %>
              <li><%= link_to "Login", new_user_session_path, :class => 'navbar-link'  %></li>
          <% end %>

        </ul>
      </nav>
    </div>
  </div>
</header>

app/views/layouts/_shim.html.erb
<!--[if lt IE 9]>
<script src="http://html5shim.googlecode.com/svn/trunk/html5.js"></script>
<![endif]-->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title><%= full_title(yield(:title)) %></title>
 	<%= stylesheet_link_tag "application", media: "all",
                          "data-turbolinks-track" => true %>
	<%= javascript_include_tag "application", "data-turbolinks-track" => true %>	
  	<%= csrf_meta_tags %>
	<meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no">
	<%= render 'layouts/shim' %>
</head>
<body>
<%= render 'layouts/header' %>
 <% flash.each do |key, value| %>
      <%= content_tag(:div, value, class: "alert alert-#{key}") %>
  <% end %>
  <div class="container">
  <%= yield %>
  </div>
  <%= render 'layouts/footer' %>
  <%= debug(params) if Rails.env.development? %>
  

</body>
</html>

app/views/layouts/home.html.erb
<!DOCTYPE html>
<html>
<head>
  <title><%= full_title(yield(:title)) %></title>
 	<%= stylesheet_link_tag "application", media: "all",
                          "data-turbolinks-track" => true %>
	<%= javascript_include_tag "application", "data-turbolinks-track" => true %>	
  	<%= csrf_meta_tags %>
	<meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no">
	<%= render 'layouts/shim' %>
</head>
<body>
<%= render 'layouts/header' %>
 <% flash.each do |key, value| %>
      <%= content_tag(:div, value, class: "alert alert-#{key}") %>
  <% end %>
  <%= yield %>
  <%= render 'layouts/footer' %>
  <%= debug(params) if Rails.env.development? %>
  

</body>
</html>

app/views/shared/_delete_topic.html.erb
<%= form_for(feed_item, url: edits_path, method: :post) do |f| %>
	<%= f.hidden_field :description, value: nil %>
 	<%= f.hidden_field :user_id, value: current_user.id if user_signed_in? %>
 	<%= f.hidden_field :topic_id, value: feed_item.id %>
	<%= f.hidden_field :chg, value: 'DELETE' %>
    <%= f.submit "Delete", class: "btn btn-sm btn-danger center-block", data: { confirm: "You sure?" }  %>
<% end %>

app/views/shared/_feed_item.html.erb
<li id="<%= feed_item.id %>">
	<div class="row">
      <div class="col-md-12">
      	<span class="user">
          <strong><%= link_to feed_item.topic.name, feed_item %></strong> 
          </span>
		    <span class="content">
          <small><%= feed_item.description %></small></span>
      	<span class="timestamp">
          Type: <%= feed_item.chg %> ago  <strong> by:  </strong>    
          <% user = User.find(feed_item.user_id) %>
          <%= user.name %>
        </span>
        <span class="navbar-right">
        	<% if user_signed_in? %>
     	    	<%= render 'edits/voting_form' , feed_item: feed_item %>
     	    	
      		<% end %>
        </span>
		  </div>
  </div>
</li>

app/views/shared/_feed_list.html.erb
<ul class="topics">
  <%= render partial: 'shared/feed_item', collection:@feed_items %>
</ul>

app/views/shared/_show_topic.html.erb
<div class="text-center">

  <p>
    <h1>The topic is...</h1>
    <h1><strong><%= topic.name %></strong></h1>
  </p>
</div>
<p class="text-center lead">
  <%= topic.description %>
</p>

<div>
  
  <strong><%=  "Added By:"  %></strong> <%=  topic.user.name if topic.user %>
</div>

app/views/static_pages/_signedin_home.html.erb
 <div class="row">
    <aside class="span4">
      <section>
        <%= render 'shared/user_info' %>
      </section>
      <section>
        <%= render 'shared/stats' %>
      </section>

      <section>
        <%= render 'shared/micropost_form' %>
      </section>
    </aside>
	<div class="span8">
      <h3>Micropost Feed</h3>
      <%= render 'shared/feed' %>
    </div>
  </div>

app/views/static_pages/about.html.erb
<% provide(:title, 'About Us') %>
<div class="container">

<h1>SciEdge</h1>
<div class="center hero-unit">
<h2>
	Defining the edge of science by outlining the questions being solved today
</h2>
</div>
</div>
</p>

app/views/topics/_form.html.erb
<%= form_for(@topic) do |f| %>
  <% if @topic.errors.any? %>
    <div id="error_explanation">
      <div class="alert alert-error">
        <%= pluralize(@topic.errors.count, "error") %> prohibited this topic from being saved:
     </div>
      <ul>
      <% @topic.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>


 <div class="row">
    <div class="col-md-3">
    </div>
    <div class="col-md-6">
	  <div class="well">
	  	<div class="text-center">
	<%= f.label :parent_node %>
	<%= f.select :parent_id, nested_set_options(Topic, @topic) {|i| "#{'-' * i.level} #{i.name}" }, required: true %>

	
    <%= f.label :topic_name %><br>
    <%= f.text_field :name %>
    </div>
  </div>
  
  <div class="well text-center">
    <%= f.label :topic_description %><br>
    <%= f.text_area :description %>
  </div>

  <div class="actions">
    <%= f.submit class: "btn btn-success" %>
  </div>
</div>
</div>
<div class="col-md-3">

<% end %>

app/views/topics/edit.html.erb
<% provide(:title, 'Edit Topic') %>

<h1>Edit a Topic</h1>

<%= render 'form' %>

<%= link_to 'Back', topics_path %>

app/views/topics/new.html.erb
<% provide(:title, 'New Topic') %>
<div class="container">
<div class="col-md-4"></div>
<div class="col-md-4">
<h2 style="text-align: center">New Topic</h2>
</div>
<div class="col-md-4"></div>
</div>
<%= render 'form' %>

<%= link_to 'Back', topics_path %>
</div>

app/views/topics/show.html.erb
<% provide(:title, @topic.name) %>

<p id="notice"><%= notice %></p>

<div class="well">
  <%= render partial: 'shared/show_topic',locals: { :topic => @topic } %>
</div>


<div class="well well-large">
	<div class="container">
<div class="col-md-4"><%= link_to 'Back', root_path, class: "btn btn-sm btn-primary center-block" %> </div>
<div class="col-md-4">
<%= render 'shared/delete_topic', feed_item: @topic %>
</div>
<div class="col-md-4"><%= link_to 'Edit', edit_topic_path(@topic), class: "btn btn-sm btn-primary center-block" %></div>
</div>
</div>